//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentSystem.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;

    public partial class tb_payment
    {
        public int cd_payment { get; set; }

        [StringLength(100, MinimumLength = 5, ErrorMessage = "The title must be at least 5 characters long")]
        [Required(ErrorMessage = "Required")]
        public string nm_payment { get; set; }

        [Required(ErrorMessage = "Required")]
        public double vl_payment { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "yyyy/mm/dd")]
        [Required(ErrorMessage = "Required")]
        public string dt_payment { get; set; }

        [DataType(DataType.Currency)]
        public double vl_tax_payment { get; set; }

        public string ds_payment { get; set; }
    }
}
